### PR TITLE
docs: add get start command

### PR DESCRIPTION
**Pull request by ryota-murakami**
I really like this project because I've learn a lot practical things from the codebase, I would say thank you so much!

In this PR, I added getting start command.
[degit](https://github.com/Rich-Harris/degit) is simple tool for clone github repo without `.git/` directory.  
That use to provide [**Vite community templete**](https://vitejs.dev/guide/#community-templates) these day,  
I don't know you'll prefer it though :)

### CODE REVIEW

**Comment by alan2207** [comment]
Hi, thanks for the contribution, I am glad you like the project :)

degit is a nice tool, however, it might be a bit confusing for those who want to contribute to the repo as git history would not be present. Let's add commands for both git clone and degit and annotate which option does what in a comment above each command, it might be a bit clearer to the user.

With the instructions you've added, we can also re-phrase line 30 a bit:

"To run the app, first create a `.env` file with the right variables - you can check `.env.example` and copy its content." to something like "To set up the app execute the following commands:".

**Comment by ryota-murakami** [comment]
@alan2207 Thank you for your decently review!  

> Let's add commands for both git clone and degit

OK, actually I've forgotten completely that this is not a starter template for bootstrap new project.
So I've got change the mind removed all git history has no benefit in the case, majority user will not do `git init` and then setup their project repository as a origin.

So I've just push the [commit](https://github.com/alan2207/bulletproof-react/pull/6/commits/647b1b4d7be992da56afc726c403337d4af2a47b)  it only git clone command written.  

Please feel free to modify if you'd like adding or fixing something!

**Comment by alan2207** [comment]
This is perfect, thanks! :)

**Comment by ryota-murakami** [comment]
@alan2207 Thanks again!

**Pull request merged**
